nodeLinker: node-modules

npmRegistries:
  "https://wp-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/WP-code-artifacts/":
    npmAlwaysAuth: true
    npmAuthToken: ${CODEARTIFACT_AUTH_TOKEN}

npmRegistryServer: "https://wp-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/WP-code-artifacts/"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
