nodeLinker: node-modules

npmRegistries:
  "https://wp-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/WP-code-artifacts/":
    npmAlwaysAuth: true
    npmAuthToken: ${WP_CODEARTIFACT_AUTH_TOKEN}

npmRegistryServer: "https://wp-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/WP-code-artifacts/"

# npmScopes:
#   fortawesome:
#     npmRegistryServer: https://npm.fontawesome.com/
#     npmAlwaysAuth: true
#     npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}

yarnPath: .yarn/releases/yarn-3.6.3.cjs
